### ISSUE TITLE
Unable to Fetch data using Vanilla JS

### ISSUE THREAD

**Issue by arafat-web** [abdulrcs/Daily-Prayer-Time-API#2]
I was trying to fetch data using Vanilla JS. But I failed and blocked by CORS policy in my chrome we browser.

**Comment by abdulrcs** [comment]
I have updated it to use `flask-cors` to support CORS in the latest commit here a060507e8fc7a0d64a04feb7e513e1eb2b78888e.

Thanks for your contribution by raising this issue @arafat-web.
